database:
  image_slider:
    columns:
      id_slide: INT AUTO_INCREMENT NOT NULL
      active: TINYINT(1) NOT NULL
      position: INT NOT NULL
      display_from: datetime DEFAULT NULL
      display_to: datetime DEFAULT NULL
    primary:
      - id_slide
    engine: InnoDb

  image_slider_lang:
    columns:
      id_slide: INT NOT NULL
      id_lang: INT NOT NULL
      title: VARCHAR(255) NOT NULL
      legend: VARCHAR(255) NOT NULL
      image: VARCHAR(255) NOT NULL
      image_mobile: VARCHAR(255) NOT NULL
      url: VARCHAR(255) NOT NULL
      description: LONGTEXT NOT NULL
    primary:
      - id_slide
      - id_lang
    engine: InnoDb

  image_slider_shop:
    columns:
      id_slide: INT NOT NULL
      id_shop: INT NOT NULL
    primary:
      - id_slide
      - id_shop
    engine: InnoDb

database_add:
  image_slider:
    columns:
      display_from: datetime DEFAULT NULL
      display_to: datetime DEFAULT NULL

database_modify:
  image_slider:
    columns:
      display_from: datetime DEFAULT NULL
      display_to: datetime DEFAULT NULL
