imports:
  - { resource: ../common.yml }

services:
  _defaults:
    public: true

  # Controller
  Oksydan\IsShoppingcart\Controller\IsShoppingCartController:
    public: true
    class: Oksydan\IsShoppingcart\Controller\IsShoppingCartController

  # config form
  oksydan.is_shoppingcart.configuration:
    class: 'Oksydan\IsShoppingcart\Form\DataConfiguration\ShoppingCartDataConfiguration'
    arguments:
      - '@prestashop.adapter.legacy.configuration'
      - '@prestashop.adapter.shop.context'
      - '@prestashop.adapter.multistore_feature'

  oksydan.is_shoppingcart.configuration.form_provider:
    class: 'Oksydan\IsShoppingcart\Form\Provider\ShoppingCartConfigurationFormDataProvider'
    arguments:
      - '@oksydan.is_shoppingcart.configuration'

  oksydan.is_shoppingcart.configuration.form_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@oksydan.is_shoppingcart.configuration.form_provider'
      - 'Oksydan\IsShoppingcart\Form\ImageSliderConfigurationType'
      - 'ConfigurationForm'

  oksydan.is_shoppingcart.form.configuration_type:
    class: 'Oksydan\IsShoppingcart\Form\ImageSliderConfigurationType'
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }
